// ocp init 测试——mkdtemp 目录内前置 git init 后实跑 runInit：
// 铺设物齐全性（目录/模板九件/doctor 模板/fence 模板/.gitignore）、幂等重跑、
// vendored 源缺失报错路径、hook 薄壳三段模板内容（D2 钉死）与 chmod。
// vendored 模板源用 fixture 目录注入，不依赖块D 交付物。
import { describe, expect, test, beforeEach, afterEach } from "bun:test";
import { existsSync, statSync } from "node:fs";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { brepoRoot } from "../cli/brepo-root";
import { runInit } from "../cli/commands/init";

/** A 仓 templates 九件文件名（vendored 副本同构） */
const TEMPLATE_NAMES = [
  "epic-spec-template.md",
  "impl-template.md",
  "issue-impl-template.md",
  "review-epic-spec-template.md",
  "review-impl-template.md",
  "review-issue-impl-template.md",
  "review-quality-gate-template.md",
  "review-spec-template.md",
  "spec-template.md",
] as const;

/** fence 模板复制源：B 仓真实 scripts/fence-template.sh（块A 自身交付物，稳定存在） */
const FENCE_SOURCE = join(brepoRoot(), "scripts", "fence-template.sh");

/** git hooks 目录（git init 后固定为 .git/hooks；hook 路径解析走 git rev-parse --git-path） */
const PRE_PUSH = ".git/hooks/pre-push";

let base: string;
let templatesSource: string;

/** 在 base 内 git init（前置条件：hook 安装依赖 git 仓库） */
function gitInit(directory: string): void {
  const result = Bun.spawnSync(["git", "init", "-q", directory], { stdout: "pipe", stderr: "pipe" });
  expect(result.exitCode).toBe(0);
}

beforeEach(async () => {
  base = await mkdtemp(join(tmpdir(), "ocp-init-test-"));
  gitInit(base);
  // fixture vendored 模板源：九件假模板（内容仅作复制与保留断言载体）
  templatesSource = await mkdtemp(join(tmpdir(), "ocp-init-fixture-"));
  for (const name of TEMPLATE_NAMES) {
    await writeFile(join(templatesSource, name), `fixture 模板：${name}\n`);
  }
});

afterEach(async () => {
  await rm(base, { recursive: true, force: true });
  await rm(templatesSource, { recursive: true, force: true });
});

/** 断言路径存在且任意执行位有效 */
function expectExecutable(path: string): void {
  expect(existsSync(path)).toBe(true);
  expect((statSync(path).mode & 0o111) !== 0).toBe(true);
}

describe("init 铺设物（D16）", () => {
  test("完整铺设：目录/模板九件/doctor 模板/fence 模板/.gitignore/hook 七件齐", async () => {
    const result = await runInit({ directory: base, hook: true, templatesSource, fenceSource: FENCE_SOURCE });
    expect(result.code).toBe(0);
    expect(result.steps.filter((step) => step.status === "failed")).toEqual([]);
    // ① plans/ 与 reviews/
    expect(existsSync(join(base, ".specpipe", "plans"))).toBe(true);
    expect(existsSync(join(base, ".specpipe", "reviews"))).toBe(true);
    // ② templates 九件（vendored 复制）
    for (const name of TEMPLATE_NAMES) {
      expect(existsSync(join(base, ".specpipe", "templates", name))).toBe(true);
    }
    // ③ doctor-config.json 模板：合法 JSON + 字段结构（D15 声明位）
    const doctorConfig = JSON.parse(await readFile(join(base, ".specpipe", "doctor-config.json"), "utf8")) as Record<string, unknown>;
    expect(doctorConfig).toEqual({ retrieval: { primary: "", fallback: "", docs: "" }, localARepoPath: "" });
    // ④ fence.sh 模板：内容与源一致 + 可执行
    expect(await readFile(join(base, ".specpipe", "fence.sh"), "utf8")).toBe(await readFile(FENCE_SOURCE, "utf8"));
    expectExecutable(join(base, ".specpipe", "fence.sh"));
    // ⑤ .gitignore：含 fence 报告条目，且绝不忽略 {wf}
    const gitignore = await readFile(join(base, ".gitignore"), "utf8");
    expect(gitignore).toContain("test-fence-reports/");
    expect(gitignore.split("\n").some((line) => line.trim().includes(".specpipe"))).toBe(false);
    // ⑥ hook 生成物：存在且可执行
    expectExecutable(join(base, PRE_PUSH));
  });

  test("hook 薄壳三段模板（D2）：ocp 优先 / bun 回退 / 双缺警告放行", async () => {
    await runInit({ directory: base, hook: true, templatesSource, fenceSource: FENCE_SOURCE });
    const hook = await readFile(join(base, PRE_PUSH), "utf8");
    const lines = hook.split("\n");
    // 首行 shebang + 文件头标识
    expect(lines[0]).toBe("#!/bin/sh");
    expect(hook).toContain("# generated by ocp init --hook");
    // 三段：ocp 优先
    expect(hook).toContain('if command -v ocp >/dev/null 2>&1; then');
    expect(hook).toContain('exec ocp hook pre-push "$@"');
    // 三段：bun 回退（B 仓 cli/index.ts 绝对路径）
    expect(hook).toContain("elif command -v bun >/dev/null 2>&1; then");
    expect(hook).toContain(`exec bun '${join(brepoRoot(), "cli", "index.ts")}' hook pre-push "$@"`);
    // 三段：双缺 echo 警告 + exit 0（不静默阻断推送）
    expect(hook).toContain('echo "ocp/bun 缺失，跳过工作流校验"');
    expect(hook).toContain("exit 0");
  });

  test("幂等重跑：既有文件跳过不覆盖、.gitignore 不重复追加、hook 幂等覆盖", async () => {
    await runInit({ directory: base, hook: true, templatesSource, fenceSource: FENCE_SOURCE });
    // 人工改动既有铺设物（模拟用户定制）
    const touchedTemplate = join(base, ".specpipe", "templates", "spec-template.md");
    await writeFile(touchedTemplate, "用户改写后的模板\n");
    await writeFile(join(base, ".specpipe", "doctor-config.json"), '{"retrieval":{"primary":"ws"},"localARepoPath":"/tmp/a"}\n');
    await writeFile(join(base, PRE_PUSH), "#!/bin/sh\nexit 0\n");
    // 重跑
    const again = await runInit({ directory: base, hook: true, templatesSource, fenceSource: FENCE_SOURCE });
    expect(again.code).toBe(0);
    // 既有文件跳过：改动保留
    expect(await readFile(touchedTemplate, "utf8")).toBe("用户改写后的模板\n");
    expect(await readFile(join(base, ".specpipe", "doctor-config.json"), "utf8")).toContain('"primary":"ws"');
    // .gitignore 条目恰一次
    const gitignoreLines = (await readFile(join(base, ".gitignore"), "utf8")).split("\n").filter((line) => line.trim() === "test-fence-reports/");
    expect(gitignoreLines.length).toBe(1);
    // hook 幂等覆盖：旧壳被模板覆盖（D2 钉死，防旧版本壳残留）
    expect(await readFile(join(base, PRE_PUSH), "utf8")).toContain("# generated by ocp init --hook");
  });

  test("vendored 模板源缺失：exit 1 + 提示先跑 vendor-sync，其余铺设物不受影响", async () => {
    const missingSource = join(base, "no-such-vendor-dir");
    const result = await runInit({ directory: base, hook: false, templatesSource: missingSource, fenceSource: FENCE_SOURCE });
    expect(result.code).toBe(1);
    const failedSteps = result.steps.filter((step) => step.status === "failed");
    expect(failedSteps.length).toBe(1);
    expect(failedSteps[0]?.detail).toContain("vendor-sync");
    // 其余铺设照常完成
    expect(existsSync(join(base, ".specpipe", "plans"))).toBe(true);
    expect(existsSync(join(base, ".specpipe", "reviews"))).toBe(true);
    expect(existsSync(join(base, ".specpipe", "doctor-config.json"))).toBe(true);
    expect(existsSync(join(base, ".specpipe", "fence.sh"))).toBe(true);
    expect(existsSync(join(base, ".specpipe", "templates"))).toBe(false);
  });

  test("未指定 --hook：不产生 pre-push", async () => {
    await runInit({ directory: base, hook: false, templatesSource, fenceSource: FENCE_SOURCE });
    expect(existsSync(join(base, PRE_PUSH))).toBe(false);
  });

  test(".gitignore 预存在条目：追加不破坏既有内容且条目恰一次", async () => {
    await writeFile(join(base, ".gitignore"), "node_modules/\n");
    await runInit({ directory: base, hook: false, templatesSource, fenceSource: FENCE_SOURCE });
    const text = await readFile(join(base, ".gitignore"), "utf8");
    expect(text.split("\n")).toContain("node_modules/");
    expect(text.split("\n").filter((line) => line.trim() === "test-fence-reports/").length).toBe(1);
    // 末尾无换行形态的追加边界
    await rm(join(base, ".gitignore"));
    await writeFile(join(base, ".gitignore"), "dist/");
    await runInit({ directory: base, hook: false, templatesSource, fenceSource: FENCE_SOURCE });
    const text2 = await readFile(join(base, ".gitignore"), "utf8");
    expect(text2.split("\n").filter((line) => line.trim() === "test-fence-reports/").length).toBe(1);
    expect(text2.split("\n").filter((line) => line.trim() === "dist/").length).toBe(1);
  });

  test("wfRoot 可配置：--wf 自定义工作流根", async () => {
    const result = await runInit({ directory: base, hook: false, wfRoot: ".workflow", templatesSource, fenceSource: FENCE_SOURCE });
    expect(result.code).toBe(0);
    expect(existsSync(join(base, ".workflow", "plans"))).toBe(true);
    expect(existsSync(join(base, ".workflow", "doctor-config.json"))).toBe(true);
  });
});

describe("hook 安装路径解析（git rev-parse --git-path）", () => {
  test("core.hooksPath 自定义时安装到配置路径", async () => {
    const customHooks = join(base, "custom-hooks");
    await mkdir(customHooks, { recursive: true });
    const config = Bun.spawnSync(["git", "-C", base, "config", "core.hooksPath", customHooks], { stdout: "pipe", stderr: "pipe" });
    expect(config.exitCode).toBe(0);
    const result = await runInit({ directory: base, hook: true, templatesSource, fenceSource: FENCE_SOURCE });
    expect(result.code).toBe(0);
    expect(existsSync(join(customHooks, "pre-push"))).toBe(true);
    expect(existsSync(join(base, PRE_PUSH))).toBe(false);
  });

  test("非 git 目录装 hook：failed 步骤 + exit 1", async () => {
    const notARepo = await mkdtemp(join(tmpdir(), "ocp-init-nogit-"));
    try {
      const result = await runInit({ directory: notARepo, hook: true, templatesSource, fenceSource: FENCE_SOURCE });
      expect(result.code).toBe(1);
      const hookStep = result.steps.find((step) => step.item === ".git/hooks/pre-push");
      expect(hookStep?.status).toBe("failed");
    } finally {
      await rm(notARepo, { recursive: true, force: true });
    }
  });
});
