// ocp init——工作流环境铺设（D16）+ pre-push 薄壳安装（D2，--hook）。
// 铺设物七件：{wf}/plans/、{wf}/reviews/、{wf}/templates/（vendored 九件复制）、
// {wf}/doctor-config.json（doctor 默认模板）、{wf}/fence.sh（fence 模板复制）、
// .gitignore 追加 test-fence-reports/（幂等；不忽略 {wf}——pre-push 校验以档案入库为前提）、
// --hook 时 .git/hooks/pre-push 薄壳。
// 已有文件/目录跳过并报告（唯一例外：hook 生成物幂等覆盖——D2 钉死，防止旧版本壳残留）。
import { existsSync } from "node:fs";
import { chmod, copyFile, mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { isAbsolute, join, resolve } from "node:path";
import { brepoRoot } from "../brepo-root";

/** 工作流根默认值（与 stage 插件 DEFAULT_WF_ROOT 一致） */
const DEFAULT_WF_ROOT = ".specpipe";

/** .gitignore 幂等追加的 fence 报告产物条目 */
const GITIGNORE_ENTRY = "test-fence-reports/";

/** doctor 配置默认模板（字段说明见 ocp doctor 输出与 D15） */
const DOCTOR_CONFIG_TEMPLATE = {
  retrieval: { primary: "", fallback: "", docs: "" },
  localARepoPath: "",
};

export interface InitOptions {
  /** 目标项目根（命令行入口传 cwd；测试注入临时目录） */
  directory: string;
  /** --hook：安装 pre-push 薄壳 */
  hook: boolean;
  /** 工作流根（相对 directory 解析），默认 ".specpipe" */
  wfRoot?: string;
  /** vendored 模板复制源目录，默认 <B仓>/configs/vendor/specpipe/templates（运行时才读取） */
  templatesSource?: string;
  /** fence 模板复制源文件，默认 <B仓>/scripts/fence-template.sh */
  fenceSource?: string;
}

export interface InitStep {
  /** 铺设物名称 */
  item: string;
  status: "created" | "skipped" | "failed";
  detail?: string;
}

export interface InitResult {
  /** 退出码：0=全部成功；1=存在失败项（其余铺设物不受影响，照常铺设） */
  code: number;
  steps: InitStep[];
}

/**
 * pre-push 薄壳模板（D2 钉死三段）：
 * ocp 优先 → bun 回退（B 仓 cli/index.ts 绝对路径）→ 双缺 echo 警告 + exit 0（不静默阻断推送）。
 */
export function hookTemplate(cliScriptPath: string): string {
  return [
    "#!/bin/sh",
    "# generated by ocp init --hook —— pre-push 薄壳；校验逻辑在 ocp hook pre-push（重跑 init --hook 幂等覆盖）",
    'if command -v ocp >/dev/null 2>&1; then',
    '  exec ocp hook pre-push "$@"',
    "elif command -v bun >/dev/null 2>&1; then",
    `  exec bun '${cliScriptPath}' hook pre-push "$@"`,
    "else",
    '  echo "ocp/bun 缺失，跳过工作流校验" >&2',
    "  exit 0",
    "fi",
    "",
  ].join("\n");
}

/** 解析 hook 安装目录：git rev-parse --git-path hooks（兼容 worktree 的 .git 文件与 core.hooksPath） */
function resolveHooksDir(directory: string): { dir: string | null; error?: string } {
  const result = Bun.spawnSync(["git", "-C", directory, "rev-parse", "--git-path", "hooks"], {
    stdout: "pipe",
    stderr: "pipe",
  });
  const stdout = result.stdout.toString().trim();
  if (result.exitCode !== 0 || !stdout) {
    const stderr = result.stderr.toString().trim();
    return { dir: null, error: stderr || "git rev-parse --git-path hooks 失败" };
  }
  // 输出可能是相对路径（普通仓 .git/hooks，相对 directory）或绝对路径（worktree / core.hooksPath）
  return { dir: isAbsolute(stdout) ? stdout : resolve(directory, stdout) };
}

/** 执行铺设。失败不中断：记录 failed 步骤后继续，最终 code=1（部分铺设仍有价值，错误信息醒目）。 */
export async function runInit(options: InitOptions): Promise<InitResult> {
  const wfRoot = options.wfRoot && options.wfRoot !== "" ? options.wfRoot : DEFAULT_WF_ROOT;
  const directory = options.directory;
  const wfDir = isAbsolute(wfRoot) ? wfRoot : resolve(directory, wfRoot);
  const steps: InitStep[] = [];
  let failed = false;

  // ① {wf}/plans/ 与 {wf}/reviews/
  for (const name of ["plans", "reviews"] as const) {
    const dir = join(wfDir, name);
    if (existsSync(dir)) {
      steps.push({ item: `{wf}/${name}/`, status: "skipped", detail: "已存在" });
    } else {
      await mkdir(dir, { recursive: true });
      steps.push({ item: `{wf}/${name}/`, status: "created" });
    }
  }

  // ② {wf}/templates/——从 vendored 副本复制（源缺失报错并提示先跑 vendor-sync，属块D 交付）
  const templatesSource = options.templatesSource ?? join(brepoRoot(), "configs", "vendor", "specpipe", "templates");
  const templatesTarget = join(wfDir, "templates");
  let sourceEntries: string[];
  try {
    sourceEntries = await readdir(templatesSource);
  } catch {
    steps.push({
      item: "{wf}/templates/",
      status: "failed",
      detail: `vendored 模板源缺失（${templatesSource}）：请先在 B 仓运行 bun scripts/vendor-sync.ts --path <A仓路径> 生成`,
    });
    failed = true;
    sourceEntries = [];
  }
  if (sourceEntries.length > 0) {
    await mkdir(templatesTarget, { recursive: true });
    let copied = 0;
    let skipped = 0;
    for (const entry of sourceEntries) {
      const target = join(templatesTarget, entry);
      if (existsSync(target)) {
        skipped += 1;
      } else {
        await copyFile(join(templatesSource, entry), target);
        copied += 1;
      }
    }
    steps.push({ item: "{wf}/templates/", status: "created", detail: `复制 ${copied} 件，跳过已存在 ${skipped} 件` });
  }

  // ③ {wf}/doctor-config.json——doctor 二级配置的项目级默认模板
  const doctorConfigPath = join(wfDir, "doctor-config.json");
  if (existsSync(doctorConfigPath)) {
    steps.push({ item: "{wf}/doctor-config.json", status: "skipped", detail: "已存在" });
  } else {
    await mkdir(wfDir, { recursive: true });
    await writeFile(doctorConfigPath, `${JSON.stringify(DOCTOR_CONFIG_TEMPLATE, null, 2)}\n`);
    steps.push({ item: "{wf}/doctor-config.json", status: "created" });
  }

  // ④ {wf}/fence.sh——fence 脚本模板（最小骨架，项目按技术栈改写）
  const fenceSource = options.fenceSource ?? join(brepoRoot(), "scripts", "fence-template.sh");
  const fenceTarget = join(wfDir, "fence.sh");
  if (existsSync(fenceTarget)) {
    steps.push({ item: "{wf}/fence.sh", status: "skipped", detail: "已存在，跳过（如需重铺先删除）" });
  } else if (!existsSync(fenceSource)) {
    steps.push({ item: "{wf}/fence.sh", status: "failed", detail: `fence 模板源缺失：${fenceSource}` });
    failed = true;
  } else {
    await mkdir(wfDir, { recursive: true });
    await copyFile(fenceSource, fenceTarget);
    await chmod(fenceTarget, 0o755);
    steps.push({ item: "{wf}/fence.sh", status: "created", detail: "模板已铺设（按项目技术栈改写步骤）" });
  }

  // ⑤ .gitignore 追加 fence 报告产物条目（幂等；绝不写入 {wf} 忽略——档案入库是 pre-push 校验前提）
  const gitignorePath = join(directory, ".gitignore");
  const gitignoreCurrent = existsSync(gitignorePath) ? await readFile(gitignorePath, "utf8") : null;
  if (gitignoreCurrent === null) {
    await writeFile(gitignorePath, `${GITIGNORE_ENTRY}\n`);
    steps.push({ item: ".gitignore", status: "created", detail: `新增 ${GITIGNORE_ENTRY}` });
  } else if (gitignoreCurrent.split("\n").some((line) => line.trim() === GITIGNORE_ENTRY)) {
    steps.push({ item: ".gitignore", status: "skipped", detail: "条目已存在" });
  } else {
    const separator = gitignoreCurrent.endsWith("\n") ? "" : "\n";
    await writeFile(gitignorePath, `${gitignoreCurrent}${separator}${GITIGNORE_ENTRY}\n`);
    steps.push({ item: ".gitignore", status: "created", detail: `追加 ${GITIGNORE_ENTRY}` });
  }

  // ⑥ --hook：pre-push 薄壳（幂等覆盖 + chmod +x）
  if (options.hook) {
    const hooks = resolveHooksDir(directory);
    if (hooks.dir === null) {
      steps.push({ item: ".git/hooks/pre-push", status: "failed", detail: `hook 安装路径解析失败：${hooks.error}` });
      failed = true;
    } else {
      const hookPath = join(hooks.dir, "pre-push");
      await mkdir(hooks.dir, { recursive: true });
      await writeFile(hookPath, hookTemplate(join(brepoRoot(), "cli", "index.ts")));
      await chmod(hookPath, 0o755);
      steps.push({ item: ".git/hooks/pre-push", status: "created", detail: `${hookPath}（幂等覆盖）` });
    }
  }

  return { code: failed ? 1 : 0, steps };
}

/** 命令行入口：--hook / --wf <path> / --help */
export async function main(args: string[], ctx: { cwd: string }): Promise<number> {
  let hook = false;
  let wfRoot: string | undefined;
  for (let i = 0; i < args.length; i += 1) {
    const arg = args[i];
    if (arg === "--hook") {
      hook = true;
    } else if (arg === "--wf") {
      wfRoot = args[i + 1];
      if (!wfRoot) {
        console.error("用法：ocp init [--hook] [--wf <工作流根>]");
        return 2;
      }
      i += 1;
    } else if (arg === "--help" || arg === "-h") {
      console.log("用法：ocp init [--hook] [--wf <工作流根>]\n铺设工作流目录/模板/fence 模板；--hook 安装 pre-push 薄壳（git rev-parse --git-path hooks 解析路径）");
      return 0;
    } else {
      console.error(`未知参数：${arg}\n用法：ocp init [--hook] [--wf <工作流根>]`);
      return 2;
    }
  }
  const result = await runInit({ directory: ctx.cwd, hook, wfRoot });
  for (const step of result.steps) {
    console.log(`[init] ${step.status} ${step.item}${step.detail ? `：${step.detail}` : ""}`);
  }
  console.log(`提示：编辑 ${wfRoot ?? DEFAULT_WF_ROOT}/doctor-config.json 声明检索三通道（retrieval.primary/fallback/docs）与本地 A 仓路径（localARepoPath）`);
  return result.code;
}
